### ISSUE TITLE
Install with Bower

### ISSUE THREAD

**Issue by pkill37** [csswizardry/typecsset#3]
Any reason why this isn't on Bower? I'd much rather run `bower install typecsset` than browse the repo and download the .scss file. Not to mention updating: `bower update` vs paying attention to the repo and downloading the file again.

**Comment by csswizardry** [comment]
Let me look into it :)

**Comment by ben-eb** [comment]
Note that you can do this with any repo that isn't published on bower; just add the repo into your `bower.json`, like so:

```
{
    "name": "My App",
    "dependencies": {
        "typecsset" : "https://github.com/csswizardry/typecsset.git#v0.3.0"
    }
}
```

Or do `bower install` where the package name is the repository endpoint.

**Comment by pkill37** [comment]
@ben-eb Good tip, thanks! :)

`bower install https://github.com/csswizardry/typecsset.git` will work for now. Hopefully #6 gets merged soon.
